// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package storage

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Order struct {
	ID         int64              `json:"id"`
	UserID     pgtype.Int8        `json:"user_id"`
	Number     string             `json:"number"`
	Status     string             `json:"status"`
	Accrual    pgtype.Float8      `json:"accrual"`
	UploadedAt pgtype.Timestamptz `json:"uploaded_at"`
}

type User struct {
	ID        int64         `json:"id"`
	Login     string        `json:"login"`
	Password  string        `json:"password"`
	Balance   pgtype.Float8 `json:"balance"`
	Withdrawn pgtype.Float8 `json:"withdrawn"`
}

type Withdrawal struct {
	ID          int64              `json:"id"`
	UserID      pgtype.Int8        `json:"user_id"`
	OrderNumber string             `json:"order_number"`
	Sum         float64            `json:"sum"`
	ProcessedAt pgtype.Timestamptz `json:"processed_at"`
}
